[package]
name = "slide-common"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1"