[package]
name = "slide-common"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
dirs = "5"
tokio = { version = "1", features = ["fs"] }