[package]
name = "slide-arg0"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "slide_arg0"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }